#!/bin/bash
if [[ $1 == "enter" ]]; then
	docker run -it --rm \
		-v $HOME/Downloads:$HOME/Downloads \
		jakdept/supermicro /bin/bash
else
	docker run -it --rm \
		-v $HOME/Downloads:$HOME/Downloads \
		jakdept/supermicro sum $*
fi
